CREATE TABLE matches
(
    id INTEGER PRIMARY KEY,
    match_date Date,
    home_team_id INTEGER,
    home_score INTEGER,
    home_manager_id INTEGER,
    away_team_id INTEGER,
    away_score INTEGER,
    away_manager_id INTEGER,
    match_week INTEGER,
    competition_id INTEGER,
    season_id INTEGER,
    referee VARCHAR(255),
    stadium VARCHAR(255),
  	CONSTRAINT fk_competition
      FOREIGN KEY (competition_id)
      REFERENCES competitions (competition_id),
    	CONSTRAINT fk_competition
      FOREIGN KEY (season_id)
      REFERENCES competitions (season_id)
);

CREATE TABLE competitions
(
    competition_id INTEGER,
    season_id INTEGER,
    competition_name VARCHAR(255),
    country_name VARCHAR(255),
    competition_gender VARCHAR(255),
    competition_youth VARCHAR(255),
    competition_international VARCHAR(255),
    season_name VARCHAR(255),
    PRIMARY KEY (competition_id, season_id)
);

CREATE TABLE teams
(
    id INTEGER PRIMARY KEY,
    country VARCHAR(255),
    name VARCHAR(255)
);

CREATE TABLE person
(
    id INTEGER PRIMARY KEY,
    name VARCHAR(255),
    country_id INTEGER
);

CREATE TABLE events
(
    id UUID PRIMARY KEY,
    x FLOAT,
    y FLOAT,
    type_id INTEGER,
    match_id BIGINT,
    player_id INTEGER,
    position_id INTEGER,
    end_x FLOAT,
    end_y FLOAT,
    timestamp TIME,
    period INTEGER,
    duration FLOAT,
    team_id INTEGER,
    play_pattern_id INTEGER,
    possession INTEGER,
    possession_team_id INTEGER,
    sub_type_id INTEGER,
    outcome_id INTEGER,
  	CONSTRAINT fk_match
      FOREIGN KEY (match_id)
      REFERENCES matches (id),
    	CONSTRAINT fk_player
      FOREIGN KEY (player_id)
      REFERENCES person (id),
    	CONSTRAINT fk_team
      FOREIGN KEY (team_id)
      REFERENCES teams (id),
    	CONSTRAINT fk_outcome
      FOREIGN KEY (outcome_id)
      REFERENCES outcomes (id),
    	CONSTRAINT fk_type
      FOREIGN KEY (type_id)
      REFERENCES event_types(id),
  		CONSTRAINT play_pattern
      FOREIGN KEY (play_pattern_id)
      REFERENCES play_patterns(id),
    		CONSTRAINT sub_type
      FOREIGN KEY (sub_type_id)
      REFERENCES event_sub_types(id),    		
  CONSTRAINT position
      FOREIGN KEY (position_id)
      REFERENCES positions(id)
  
  
);

CREATE TABLE event_types
(
    id INTEGER PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE passes
(
    id UUID PRIMARY KEY,
    recipient_id INTEGER,
    pass_length FLOAT,
    pass_angle FLOAT,
    pass_height VARCHAR(255),
    assisted_shot_id UUID
);

CREATE TABLE shots
(
    id UUID PRIMARY KEY,
    statsbomb_xg FLOAT,
    first_time BOOLEAN,
    technique_id INTEGER,
    key_pass_id UUID,
    one_on_one BOOLEAN
);


CREATE TABLE player_positions
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teammate BOOLEAN,
    x FLOAT,
    y FLOAT,
    match_id INTEGER,
    event_id UUID,
  CONSTRAINT fk_match
      FOREIGN KEY (match_id)
      REFERENCES matches (id),
      	CONSTRAINT fk_event
      FOREIGN KEY (event_id)
      REFERENCES events (id)
);

CREATE TABLE play_patterns
(
    id INTEGER PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE event_sub_types
(
    id INTEGER PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE outcomes
(
    id INTEGER PRIMARY KEY,
    name VARCHAR(255)
);


CREATE TABLE positions
(
    id INTEGER PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE techniques
(
    id INTEGER PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE possessions
(
    match_id INTEGER,
    possession INTEGER,
    passes INTEGER,
    carry INTEGER,
    dribble INTEGER,
    shot INTEGER,
    duel INTEGER,
    pressure INTEGER,
    block INTEGER,
    ball_recovery INTEGER,
    interception INTEGER,
    clearance INTEGER,
    avg_pass_length FLOAT,
    pass_success_rate FLOAT,
    possession_team_name VARCHAR(255),
    playing_style VARCHAR(255),
  	CONSTRAINT fk_match
      FOREIGN KEY (match_id)
      REFERENCES matches (id)
);


