CREATE TABLE matches
(
    id INTEGER PRIMARY KEY,
    match_date Date,
    home_team_id INTEGER,
    home_score INTEGER,
    home_manager_id INTEGER,
    away_team_id INTEGER,
    away_score INTEGER,
    away_manager_id INTEGER,
    match_week INTEGER,
    competition_id INTEGER,
    season_id INTEGER,
    referee VARCHAR(255),
    stadium VARCHAR(255)
);

CREATE TABLE competitions
(
    competition_id INTEGER,
    season_id INTEGER,
    competition_name VARCHAR(255),
    country_name VARCHAR(255),
    competition_gender VARCHAR(255),
    competition_youth VARCHAR(255),
    competition_international VARCHAR(255),
    season_name VARCHAR(255),
    PRIMARY KEY (competition_id, season_id)
);

CREATE TABLE teams
(
    id INTEGER PRIMARY KEY,
    country VARCHAR(255),
    name VARCHAR(255)
);

CREATE TABLE person
(
    id INTEGER PRIMARY KEY,
    name VARCHAR(255),
    country_id INTEGER
);

CREATE TABLE events
(
    id UUID PRIMARY KEY,
    x FLOAT,
    y FLOAT,
    type_id INTEGER,
    match_id BIGINT,
    player_id INTEGER,
    position_id INTEGER,
    end_x FLOAT,
    end_y FLOAT,
    timestamp TIME,
    period INTEGER,
    duration FLOAT,
    team_id INTEGER,
    play_pattern_id INTEGER,
    possession INTEGER,
    possession_team_id INTEGER,
    sub_type_id INTEGER,
    outcome_id INTEGER
);

CREATE TABLE event_types
(
    id INTEGER PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE passes
(
    id UUID PRIMARY KEY,
    recipient_id INTEGER,
    pass_length FLOAT,
    pass_angle FLOAT,
    pass_height VARCHAR(255),
    assisted_shot_id UUID
);

CREATE TABLE shots
(
    id UUID PRIMARY KEY,
    statsbomb_xg FLOAT,
    first_time BOOLEAN,
    technique_id INTEGER,
    key_pass_id UUID,
    one_on_one BOOLEAN
);


CREATE TABLE player_positions
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teammate BOOLEAN,
    x FLOAT,
    y FLOAT,
    match_id INTEGER,
    event_id UUID,
    player_id INTEGER,
    position_id INTEGER
);

CREATE TABLE play_patterns
(
    id INTEGER PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE event_sub_types
(
    id INTEGER PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE outcomes
(
    id INTEGER PRIMARY KEY,
    name VARCHAR(255)
);


CREATE TABLE positions
(
    id INTEGER PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE techniques
(
    id INTEGER PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE possessions
(
    match_id INTEGER,
    possession INTEGER,
    passes INTEGER,
    carry INTEGER,
    dribble INTEGER,
    shot INTEGER,
    duel INTEGER,
    pressure INTEGER,
    block INTEGER,
    ball_recovery INTEGER,
    interception INTEGER,
    clearance INTEGER,
    avg_pass_length FLOAT,
    pass_success_rate FLOAT,
    possession_team_name VARCHAR(255),
    playing_style VARCHAR(255)
);

CREATE TABLE playing_times
(
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    match_id INTEGER,
    player_id INTEGER,
    player_name VARCHAR(255),
    start_period INTEGER,
    start_time TIME,
    end_period INTEGER,
    end_time TIME,
    minutes INTEGER
);

CREATE TABLE player_stats
(
    id INTEGER,
    minutes INTEGER,
    pass_90 FLOAT,
    carry_90 FLOAT,
    dribble_90 FLOAT,
    shot_90 FLOAT,
    duel_90 FLOAT,
    pressure_90 FLOAT,
    block_90 FLOAT,
	ball_recovery_90 FLOAT,
	interception_90 FLOAT,
    clearance_90 FLOAT,
    foul_won_90 FLOAT,
    foul_commited_90 FLOAT,
    avg_pass_length FLOAT,
    longest_forward_pass FLOAT,
    average_shot_length FLOAT,
	header_percent FLOAT,
    xg_90 FLOAT,
	dribble_percent FLOAT,
	average_dribble_start_x FLOAT,
	ground_pass_percent FLOAT,
	low_pass_percent FLOAT,
	high_pass_percent FLOAT,
	goalkeeper FLOAT,
	center_back FLOAT,
	wide_back FLOAT,
	center_midfielder FLOAT,
	wide_midfielder FLOAT,
	striker FLOAT,
	defensive_start_percent FLOAT,
	middle_start_percent FLOAT,
	attacking_start_percent FLOAT,
    pass_percent FLOAT,
    duel_rate_percent FLOAT,
    save_percent FLOAT,
    shot_on_target_percent FLOAT,
    shot_goal_percent FLOAT,
    pass_success_rate_percent FLOAT,
    extra_shots_percent FLOAT,
    first_time_shots_percent FLOAT,
    shots_on_target_percent FLOAT,
    assists_90 FLOAT,
    goals_90 FLOAT,
    cluster VARCHAR(100)
);